### ISSUE TITLE
Building RPM for Badlock

### ISSUE THREAD

**Issue by DavidePrincipi** [opinkerfi/winexe-waf#2]
On CentOS 6, after installing the Samba security update for Badlock vulnerability, I ran into a RPM dependency problem with `winexe-1.1-1.git.0.9d83c1e.el6.x86_64`. 

```
Error: Package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64 (nethserver-base)
           Requires: libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit)
           Available: samba4-libs-4.0.0-66.el6_6.rc4.x86_64 (base)
               libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit)
           Available: samba4-libs-4.0.0-67.el6_7.rc4.x86_64 (updates)
               libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit)
           Available: samba4-libs-4.0.0-68.el6_7.rc4.x86_64 (updates)
               libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit)
           Installed: samba4-libs-4.2.10-6.el6_7.x86_64 (@updates)
               Not found
Error: Package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64 (nethserver-base)
           Requires: libcli-ldap.so(SAMBA_4.0.0RC4)(64bit)
           Available: samba4-libs-4.0.0-66.el6_6.rc4.x86_64 (base)
               libcli-ldap.so(SAMBA_4.0.0RC4)(64bit)
           Available: samba4-libs-4.0.0-67.el6_7.rc4.x86_64 (updates)
               libcli-ldap.so(SAMBA_4.0.0RC4)(64bit)
           Available: samba4-libs-4.0.0-68.el6_7.rc4.x86_64 (updates)
               libcli-ldap.so(SAMBA_4.0.0RC4)(64bit)
           Installed: samba4-libs-4.2.10-6.el6_7.x86_64 (@updates)
               Not found
Error: Package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64 (nethserver-base)
           Requires: liberrors.so()(64bit)
           Available: samba4-libs-4.0.0-66.el6_6.rc4.x86_64 (base)
               liberrors.so()(64bit)
           Available: samba4-libs-4.0.0-67.el6_7.rc4.x86_64 (updates)
               liberrors.so()(64bit)
           Available: samba4-libs-4.0.0-68.el6_7.rc4.x86_64 (updates)
               liberrors.so()(64bit)
           Installed: samba4-libs-4.2.10-6.el6_7.x86_64 (@updates)
               Not found
Error: Package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64 (nethserver-base)
           Requires: libcli-ldap.so()(64bit)
           Available: samba4-libs-4.0.0-66.el6_6.rc4.x86_64 (base)
               libcli-ldap.so()(64bit)
           Available: samba4-libs-4.0.0-67.el6_7.rc4.x86_64 (updates)
               libcli-ldap.so()(64bit)
           Available: samba4-libs-4.0.0-68.el6_7.rc4.x86_64 (updates)
               libcli-ldap.so()(64bit)
           Installed: samba4-libs-4.2.10-6.el6_7.x86_64 (@updates)
               Not found
Error: Package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64 (nethserver-base)
           Requires: liberrors.so(SAMBA_4.0.0RC4)(64bit)
           Available: samba4-libs-4.0.0-66.el6_6.rc4.x86_64 (base)
               liberrors.so(SAMBA_4.0.0RC4)(64bit)
           Available: samba4-libs-4.0.0-67.el6_7.rc4.x86_64 (updates)
               liberrors.so(SAMBA_4.0.0RC4)(64bit)
           Available: samba4-libs-4.0.0-68.el6_7.rc4.x86_64 (updates)
               liberrors.so(SAMBA_4.0.0RC4)(64bit)
           Installed: samba4-libs-4.2.10-6.el6_7.x86_64 (@updates)
               Not found
Error: Package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64 (nethserver-base)
           Requires: libdcerpc-samba.so()(64bit)
           Available: samba4-libs-4.0.0-66.el6_6.rc4.x86_64 (base)
               libdcerpc-samba.so()(64bit)
           Available: samba4-libs-4.0.0-67.el6_7.rc4.x86_64 (updates)
               libdcerpc-samba.so()(64bit)
           Available: samba4-libs-4.0.0-68.el6_7.rc4.x86_64 (updates)
               libdcerpc-samba.so()(64bit)
           Installed: samba4-libs-4.2.10-6.el6_7.x86_64 (@updates)
               Not found

```

I tried to recompile it from this git repo against the new Samba version but I ran into trouble! Could you have a glance at it?

**Comment by hakong** [comment]
Just spoke to @tryggvi on the phone, and he said they will have this looked at shortly. @gardart will be working this.

**Comment by aflat** [comment]
You can build if you apply this patch. Looks like samba 4.2 appended samb4 to some of their libraries

```
From da995420b284374ccb9019413dd23baaf95ac13e Mon Sep 17 00:00:00 2001
From: George Stockfisch <gstock.public@gmail.com>
Date: Thu, 21 Apr 2016 15:53:14 +0000
Subject: [PATCH] edit config to take into account the new samba lib names

---
 source/wscript | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/source/wscript b/source/wscript
index 361be52..4210c2d 100644
--- a/source/wscript
+++ b/source/wscript
@@ -55,9 +55,9 @@ def configure(ctx):
         else:
             import subprocess
             for subdir in 'samba private'.split():
-                p = subprocess.Popen(['gcc', '-print-file-name=%s/libcli-ldap.so' % (subdir)], stdout=subprocess.PIPE).communicate()[0].rstrip()
+                p = subprocess.Popen(['gcc', '-print-file-name=%s/libcli-ldap-samba4.so' % (subdir)], stdout=subprocess.PIPE).communicate()[0].rstrip()
                 if not os.path.exists(p):
-                    p = subprocess.Popen(['gcc', '-print-file-name=%s/libcli-ldap.so.0' % (subdir)], stdout=subprocess.PIPE).communicate()[0].rstrip()
+                    p = subprocess.Popen(['gcc', '-print-file-name=%s/libcli-ldap-samba4.so.0' % (subdir)], stdout=subprocess.PIPE).communicate()[0].rstrip()
                 if not os.path.exists(p):
                     continue
                 ctx.env.SAMBA_LIBS = os.path.abspath(p + '/..')
@@ -78,7 +78,7 @@ def configure(ctx):
                 ''' % (h in 'smb_cli.h smb_cliraw.h smb_composite.h util/debug.h'.split(), h))

             libs = []
-            for l in 'cli-ldap dcerpc dcerpc-samba errors popt talloc ndr-standard samba-hostconfig samba-credentials smbclient-raw'.split():
+            for l in 'cli-ldap-samba4 dcerpc-samba4 dcerpc-samba-samba4 errors-samba4 popt talloc ndr-standard samba-hostconfig samba-credentials smbclient-raw'.split():
                 if ctx.check(lib=l, libpath=ctx.env.SAMBA_LIBS, mandatory=False):
                     libs.append(l)
                 else:
--
2.6.3
```

**Comment by hakong** [comment]
@aflat can you make a pull request?

**Comment by gsanchietti** [comment]
I'm trying to build the RPM on CentOS but I have no luck.
I had to install also following dependencies:
`yum install gnutls-devel libacl-devel openldap-devel`

But I hit this bug when compiling in static mode:

```
Checking compiler for full RELRO support                                                        : yes 
Checking if toolchain accepts -fstack-protector                                                 : yes 
'configure' finished successfully (45.032s)
    Selected embedded Heimdal build
Waf: Entering directory `/root/samba/bin'
    Selected embedded Heimdal build
[3371/3853] Compiling default/source/smb_static/smb_static.objlist.empty.c
Waf: Leaving directory `/root/samba/bin'
Build failed: could not find 'source/smb_static/smb_static.objlist.empty.c' for 
    {task: cc smb_static.objlist.empty.c -> smb_static.objlist.empty_2.o}
Checking for library smb_static                     : not found 
Build of static winexe                              : disabled 
Cannot continue! Please either install Samba shared libraries and re-run waf, or download the Samba source code and re-run waf with the "--samba-dir" option.
(complete log in /root/winexe-waf/source/build/config.log)

```

Extract from config.log:

```
Checking for library smb_static
==>

int main(int argc, char **argv) {
        return 0;
}

<==
[1/2] ESC[32mc: build/.conf_check_c9a2c9c5521a4b99c29f03ad72546a50/test.c -> build/.conf_check_c9a2c9c5521a4b99c29f03ad72546a50/testbuild/test.c.1.o
ESC[0m
['/usr/bin/gcc', '../test.c', '-c', '-o', 'test.c.1.o']
[2/2] ESC[33mcprogram: build/.conf_check_c9a2c9c5521a4b99c29f03ad72546a50/testbuild/test.c.1.o -> build/.conf_check_c9a2c9c5521a4b99c29f03ad72546a50/testbuild/testprog
ESC[0m
['/usr/bin/gcc', 'test.c.1.o', '-o', '/root/winexe-waf/source/build/.conf_check_c9a2c9c5521a4b99c29f03ad72546a50/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L/root/winexe-waf/source/smb_static/build', '-lsmb_static']
err: /usr/bin/ld: cannot find -lsmb_static
collect2: ld returned 1 exit status

from /root/winexe-waf/source: Test does not build: Traceback (most recent call last):
  File "/root/winexe-waf/source/.waf-1.7.5-47d5afdb5e7e2856f7f46a7101914026/waflib/Tools/c_config.py", line 451, in run_c_code
    bld.compile()
  File "/root/winexe-waf/source/.waf-1.7.5-47d5afdb5e7e2856f7f46a7101914026/waflib/Build.py", line 198, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed (exit status 1): 
        {task 32946448: cprogram test.c.1.o -> testprog}
['/usr/bin/gcc', 'test.c.1.o', '-o', '/root/winexe-waf/source/build/.conf_check_c9a2c9c5521a4b99c29f03ad72546a50/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L/root/winexe-waf/source/smb_static/build', '-lsmb_static']

not found
from /root/winexe-waf/source: The configuration failed

```

Have you got any hint on this?

Thanks!

**Comment by hakong** [comment]
I think @gardart released a new winexe-waf package the other day. winexe-waf 1.1-2. Could this be related to that?

**Comment by gsanchietti** [comment]
Where can I find the released package?

**Comment by hakong** [comment]
Found it in the testing repo for el6: http://opensource.is/repo/testing/rhel6/x86_64/

**Comment by gsanchietti** [comment]
The RPM correctly works on CentOS 6.8. 
Thanks to @nrauso for the tests.

**Comment by gardart** [comment]
Thats great to hear, thanks

**Comment by gardart** [comment]
new package, version 1.1-2 released here http://opensource.is/repo/testing/rhel6/x86_64/
